# Etapa 1: Build
FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Nginx expone 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
